// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package domain

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 域表
type Domain struct {
	ID int32
	// 域名称
	Domain string
	// 状态
	Status int32
	// 创建时间
	Created pgtype.Timestamp
}
