// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDomain = "Domains"

// Domain 域表
type Domain struct {
	ID      int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:域ID" json:"id"` // 域ID
	Domain  string    `gorm:"column:domain;not null;comment:域名称" json:"domain"`              // 域名称
	Status  int32     `gorm:"column:status;not null;comment:状态" json:"status"`               // 状态
	Created time.Time `gorm:"column:created;comment:创建时间" json:"created"`                    // 创建时间
}

// TableName Domain's table name
func (*Domain) TableName() string {
	return TableNameDomain
}
