// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRole = "Roles"

// Role 角色表
type Role struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:角色ID" json:"id"` // 角色ID
	Rolename string    `gorm:"column:rolename;not null;comment:角色名称" json:"rolename"`          // 角色名称
	Status   int32     `gorm:"column:status;not null;comment:状态" json:"status"`                // 状态
	Created  time.Time `gorm:"column:created;comment:创建时间" json:"created"`                     // 创建时间
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
