// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "Users"

// User 用户表
type User struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户ID" json:"id"` // 用户ID
	Nickname string    `gorm:"column:nickname;comment:昵称" json:"nickname"`                     // 昵称
	Username string    `gorm:"column:username;not null;comment:用户名" json:"username"`           // 用户名
	Password string    `gorm:"column:password;not null;comment:密码" json:"password"`            // 密码
	Sex      string    `gorm:"column:sex;comment:性别" json:"sex"`                               // 性别
	Email    string    `gorm:"column:email;not null;comment:邮箱" json:"email"`                  // 邮箱
	Status   int32     `gorm:"column:status;not null;comment:状态" json:"status"`                // 状态
	Created  time.Time `gorm:"column:created;comment:创建时间" json:"created"`                     // 创建时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
