// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package user

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 用户表
type User struct {
	ID int32
	// 昵称
	Nickname pgtype.Text
	// 用户名
	Username string
	// 密码
	Password string
	// 性别
	Sex pgtype.Text
	// 邮箱
	Email string
	// 状态
	Status int32
	// 创建时间
	Created pgtype.Timestamp
}
